### ISSUE TITLE
Error with unpacking

### ISSUE THREAD

**Issue by FLAK-ZOSO** [FLAK-ZOSO/Prompt#10]
This function in [`parsing.py`](https://github.com/FLAK-ZOSO/Prompt/blob/v0.5.0-beta/parsing.py) is supposed to unpack the full input string:
```python
def command(full_command: str, expected: int) -> (tuple[int, Any] | None):
    list_ = full_command.split()
    
    if (not len(list_)-1):
        for i in range(4):
            yield 0
        return

    yield len(list_)-1
    command_name = list_[0]
    if (list_.remove(command_name)):
        for i in list_:
            yield i
    for i in range(expected - len(list_) - 1):
        yield 0
```

But when called in [`commands.setVar`](https://github.com/FLAK-ZOSO/Prompt/blob/ed683d8d49cc3209dc3441b4823de45066024fb8/commands.py#L55) with the arguments passed in line...
```python
def setVar(full_command: str) -> None:
    _, var, val, typ = p.command(full_command, 4)
```

...like this...
```
9: C:\> setVar age 18 int
```
...this error is raised:
```python
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    main()
  File "D:\Python\Python\Prompt\main.py", line 12, in main
    if (p.main()):
  File "D:\Python\Python\Prompt\perform.py", line 19, in main
    commands[command.split()[0].lower()](command)
  File "D:\Python\Python\Prompt\commands.py", line 56, in setVar
    _, var, val, typ = p.command(full_command, 4)
ValueError: not enough values to unpack (expected 4, got 1)
```

**Comment by FLAK-ZOSO** [comment]
I pasted [`here`](https://gist.github.com/FLAK-ZOSO/033d4b821fe5df7d8df00725327132b0) the answer suggested on Python's Discord server.

Lets see if it works.
