### ISSUE TITLE
Input only spaces

### ISSUE THREAD

**Issue by FLAK-ZOSO** [FLAK-ZOSO/Prompt#5]
This error is raised when the command is made out of only spaces (it's a common error to send a wrong space key):

```python
Traceback (most recent call last):
  File "D:\Python\Python\Prompt\main.py", line 18, in <module>
    main()
  File "D:\Python\Python\Prompt\main.py", line 13, in main
    if (p.main()):
  File "D:\Python\Python\Prompt\perform.py", line 65, in main
    commands[command.split()[0].lower()](command)
IndexError: list index out of range
```

So this should be fixed.

**Comment by FLAK-ZOSO** [comment]
https://stackoverflow.com/questions/2405292/check-if-string-contains-only-whitespace

**Comment by FLAK-ZOSO** [comment]
Just need to add `command.isspace()` as a condition.

```python
if (command == '' or command.isspace()):
    v.incrementLine(1)
    return False
```
