### ISSUE TITLE
Error with command directory

### ISSUE THREAD

**Issue by FLAK-ZOSO** [FLAK-ZOSO/Prompt#7]
An error is raised when trying to pass one argument to command `directory`:

```python
9: D:\> directory f

Traceback (most recent call last):
  File "D:\Python\Python\Prompt\main.py", line 17, in <module>
    main()
  File "D:\Python\Python\Prompt\main.py", line 12, in main
    if (p.main()):
  File "D:\Python\Python\Prompt\perform.py", line 28, in main
    commands[command.split()[0].lower()](command)
  File "D:\Python\Python\Prompt\directory.py", line 94, in main
    arg, name, dept, sub = p.command(full_command)
  File "D:\Python\Python\Prompt\parsing.py", line 24, in command
    for i in list_.remove(command_name):
TypeError: 'NoneType' object is not iterable
```

---

The error occurs any way the `directory` command is invoked.

**Comment by FLAK-ZOSO** [comment]
I'm sure it depends on [`parsing.py`](https://github.com/FLAK-ZOSO/Prompt/blob/a917b367b49e2ea9e716eb10d407ffe86f3f446f/parsing.py#L20), lets fill this file with `breakpoint`s and do some debugging.

**Comment by FLAK-ZOSO** [comment]
Error solved, it was depending on the unpacking of the `tuple` created by the `yield`s of the `parsing.command` function.
https://github.com/FLAK-ZOSO/Prompt/releases/tag/v0.4.2
